### ISSUE TITLE
[GENERAL] Package takeover

### ISSUE THREAD

**Issue by vivi90** [atom-extensions/atom-music#19]
> Hey sorry for the late response
> 
> The playlist if saved in the serialized state of the package.
> 
> I am not mainitng the package anymore and I noticed that you have forked the repo and have create mitsu.
> 
> If you want you can takeover this package.
> 
> Thanks,
> Dinesh

@sdinesh86 Is it possible, that i get write access of the repository settings? 
Want to add some documentation later.

**Comment by sdinesh86** [comment]
I have already added you as collaborator, can you check it once again

**Comment by vivi90** [comment]
@sdinesh86 Unfortunately there is no settings tab.

**Comment by vivi90** [comment]
What i want to do soon:
 * add GitHub Pages based documentation (will add some plug in settings later)
 * implement CI/CD with Travis CI (so maybe i need to change some settings).

**Comment by UziTech** [comment]
> implement CI/CD with Travis CI

I would recommend using GitHub Actions for CI/CD. I maintain many Atom packages that use it. You can look at [sync-settings](https://github.com/atom-community/sync-settings/blob/master/.github/workflows/ci.yml) as an example.

**Comment by vivi90** [comment]
@sdinesh86 It seems, that the only way is to transfer this repo to an new created "organization".
See here: https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository#collaborator-access-on-a-repository-owned-by-a-user-account

> Tip: If you require more granular read/write access to a repository owned by your user account, 
> consider transferring the repository to an organization. For more information, see "Transferring a repository."

@UziTech I wanted to use this example: https://github.com/atom/ci/blob/master/.travis.yml
But your way sounds interesting, so will i give it a try. :-)
Btw: the spec tests are failing and i am still not familiar with Jasmine. 
Would be great, if you have an idea: https://github.com/sdinesh86/atom-music/issues/17

**Comment by UziTech** [comment]
I'll take a look at the tests tonight and maybe do a PR for GitHub actions. 😁

**Comment by vivi90** [comment]
@UziTech If you also create an GitHub Actions file, then may you please name the workflow "build"? :-)
Because i want to add later such fancy badge to the README file for the users like here:  https://github.com/vivi90/mitsu
(Btw.: I will unpublish and delete the mitsu package later.)

**Comment by vivi90** [comment]
Update: Mitsu package unpublished.

**Comment by UziTech** [comment]
FYI you might want to look at [music-time](https://atom.io/packages/music-time) for some inspiration. Just released Yesterday.

**Comment by vivi90** [comment]
@UziTech Thank you for this tip. It seems, that music-time needs Spotify. I want to avoid such requirements and keep atom-music independent.
If you just push a fix for the broken specs, then i will do the other stuff.
Otherwise i will soon remove the specs for now to avoid build failing status.
(Yes i know, bad idea.)

**Comment by vivi90** [comment]
@sdinesh86 We need access to the repository settings. Otherwise it's hard to continue it.
See here: https://github.com/sdinesh86/atom-music/pull/23

For me there are 3 possibilities:
 * Move this repository to a new created GitHub organization and grant @UziTech or me more rights.
 * Move this repository to @UziTech or me (Change owner).
 * Continue with a fork of this repository (then we will loose the stars and download counter at atom.io).

**Comment by sdinesh86** [comment]
First option seems to be more better.

What do you think for the name of the organization ?

**Comment by UziTech** [comment]
How about "mitsu"?

**Comment by UziTech** [comment]
Or just atom-music

**Comment by sdinesh86** [comment]
btw what does mitsu mean, in this case

**Comment by vivi90** [comment]
"atom-extensions" is fine.
Mitsu was the name of my fork of atom-music.
This word is japanese and means different things, depending on how it is written.
My idea was 「蜜」, what means nectar or honey (See: https://jisho.org/search/%E8%9C%9C).
Because for me is music also something sweet, what i need for coding. :-)

**Comment by vivi90** [comment]
@sdinesh86 We still need settings access.
So i recommend to do it by creating a team "maintainers" for it.

 1. Enable team discussions (optional but nice to have): https://github.com/organizations/atom-extensions/settings/teams
 2. Create new team "maintainers": https://github.com/orgs/atom-extensions/new-team
 3. Add repository "atom-music" to team "maintainers": https://github.com/orgs/atom-extensions/teams/maintainers/repositories
 4. Change permission level to "Maintain" at the same link.

For more about permissions see here: 
https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization

//EDIT:
Steps 1 and 2 already done.
For step 3 i get: 'You do not have sufficient permissions to add the atom-music repository to this team'

**Comment by sdinesh86** [comment]
done check it once

**Comment by vivi90** [comment]
@sdinesh86 To grant the whole team this access by step 3 and 4 would be better.
Now i have maintain permissions but still not able to add tokens are needed here: https://github.com/atom-extensions/atom-music/pull/23
At least the settings for GitHub Pages are now available.

**Comment by sdinesh86** [comment]
I have done that too

**Comment by vivi90** [comment]
Project reorganization done.
So i close this issue.
